export const GET_CATEGORIES = "GET_CATEGORIES";
export const POST_CATEGORIES = "POST_CATEGORIES";
export const GET_EVENTS = "GET_EVENTS";
export const POST_EVENTS = "POST_EVENTS";
export const GET_PAGECATEGORIES = "GET_PAGECATEGORIES";
